
- hosts: appserver
  vars: 
    name: Azure
  tasks: 
    - name: Replace string
      replace:
         path: /home/cloud-user/configuration.txt
         regexp: 'AWS'
         replace: '{{ name }}'
